apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: inventory
type: Opaque
stringData:
  POSTGRES_DB: inventorydb
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: changeme-use-strong-password
---
apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: inventory
type: Opaque
stringData:
  DB_PASSWORD: changeme-use-strong-password
